### ISSUE TITLE
Analog display issues.

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Arcade-Breakout_MiSTer#3]
This core is the only one that I have issues with on my consumer trinitron. 

Top part of the screen is warped and not sync'd correctly.  It's odd, only like 20% of the screen at top, and the rest is fine.  Makes the game unplayable on CRT.

**Comment by bellwood420** [comment]
As I noted on readme, analog video output is not guaranteed.
The video timing generated from the original circuit is far from NTSC standard, and the core is using it as-is.

To be specific, VSYNC is extremely too long (see attached image)

<img width="1202" alt="VSYNC" src="https://user-images.githubusercontent.com/50853463/122341771-d0275680-cf7e-11eb-83b0-c850f25f1deb.png">

This might reasonably explain the reported behavior.
> Top part of the screen is warped and not sync'd correctly. It's odd, only like 20% of the screen at top, and the rest is fine.

**Comment by bellwood420** [comment]
Regenerating better VSYNC may solve the issue, but unfortunately I don't have any CRTs to test on.
 
@M-Walrus Could you try attached test build if possible?

[Arcade-Breakout_20210617.zip](https://github.com/MiSTer-devel/Arcade-Breakout_MiSTer/files/6667999/Arcade-Breakout_20210617.zip)

**Comment by M-Walrus** [comment]
> 
> 
> Regenerating better VSYNC may solve the issue, but unfortunately I don't have any CRTs to test on.
> 
> @M-Walrus Could you try attached test build if possible?
> 
> [Arcade-Breakout_20210617.zip](https://github.com/MiSTer-devel/Arcade-Breakout_MiSTer/files/6667999/Arcade-Breakout_20210617.zip)

I just tested, and analog output is perfect for me with this build.  No sync issues at all.  Nice & quick fix.  Could this maybe be added as an OSD option so folks with a standard NTSC tv can use it this way, while folks that want to use it on an arcade monitor can retain the original values?

**Comment by bellwood420** [comment]
@M-Walrus Thanks for testing :)

> Could this maybe be added as an OSD option

Yes. I added "VSYNC" option on OSD in attached new test build. I'd appreciate it if you could check again.
[Arcade-Breakout_20210618.zip](https://github.com/MiSTer-devel/Arcade-Breakout_MiSTer/files/6674710/Arcade-Breakout_20210618.zip)

I will make a release after it is confirmed.

**Comment by dfilskov** [comment]
Great work, guys!

**Comment by M-Walrus** [comment]
> Yes. I added "VSYNC" option on OSD in attached new test build. I'd appreciate it if you could check again.
> [Arcade-Breakout_20210618.zip](https://github.com/MiSTer-devel/Arcade-Breakout_MiSTer/files/6674710/Arcade-Breakout_20210618.zip)
> 
> I will make a release after it is confirmed.

The option works as expected on my CRT, but strangely modifies the size of integer output on HDMI. seems too small a step to be retaining integer, so I suspect something is off there. Besides that it is ready to go.

Thanks for your work.

**Comment by bellwood420** [comment]
> but strangely modifies the size of integer output on HDMI.

That's a good observation. I didn't notice it.
I also get the following resolution report.

```
[TV Compatible] Video resolution: 349 x 228, fHorz = 16.0KHz, fVert = 63.4Hz, fPix = 7.16MHz
[Original     ] Video resolution: 349 x 223, fHorz = 16.0KHz, fVert = 63.4Hz, fPix = 7.16MHz
```

But, the appearance on my monitor doesn't change.
How about you @M-Walrus ?

---
The scaler uses blanking signals (HBLANK, VBLANK) to identify the active pixel and line, which don't exist in the original circuit, so these are defined specifically for this core.

Looking at the waveform I posted before, the original VSYNC overlaps the active video line.
Normally, VSYNC is included in the period of VBLANK, but in this case, a part of VSYNC is out of VBLANK.

The scaler may be actually working true to VBLANK, but as for the resolution report, it may consider VSYNC outside of VBLANK as a part of VBLANK.

---
**EDIT:**
I looked into the framework a bit.
Resolution report to Main_MiSTer(Linux part) is not from the scaler.
It is calculated independently by other module than the scaler.
I haven't looked into the logic in detail, but it is possible that there is a difference between scaler and resolution calculator for treating irregular blanking/sync signals

**Comment by M-Walrus** [comment]
No, on CRT I do not notice any size difference, only sync correction occurs when that is toggled.  Exclusively HDMI integer output gets slightly different size, as far as I can tell.  Fullscreen output is probably scaling from this differently reported resolution as well, but I can't tell if it is, since it looks the same to me.

**Comment by bellwood420** [comment]
I've recreated and understood your situation by enabling integer scaling.
I had not noticed since my `vscale_mode` was set to 0! I think I misunderstood.

To sum up, the input vertical resolution that the scaler senses also changes the same way as the reported resolution due to VSYNC correction. Then it affects the calculation of integer scaling.

This behavior is understandable but cannot be helped.
- The difference in resolution is caused by the fact that the original VSYNC is out of spec
- It's not particularly a bug (no missing display area, just scaling ratio changes a bit)
- VSYNC option is not for HDMI

So I'll leave it as is.

Thank you so much for your cooperation :)
